version: "3.9"

services:
  angular-app:
    container_name: angular-app
    build:
      context: ./angular-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - ms-network

  eureka:
    container_name: eureka
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - ms-network
    restart: unless-stopped
    environment:
      - eureka.instance.hostname=eureka
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

  mysql-stock:
    container_name: mysql-stock
    image: mysql:8
    networks:
      - local-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=stock
    restart: unless-stopped

  stock:
    container_name: stock
    build:
      context: ./stock
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - local-mysql
      - ms-network
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-stock:3306/stock?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    depends_on:
      - mysql-stock

networks:
  local-mysql:
  ms-network:
    driver: bridge
